spring:
  application:
    name: currency-exchange-service
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      host: localhost
      port: 27017
      database: currency-conversion

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
      show_sql: true
      format_sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/micro
    username: root
    password: Hash@123
server:
  port: 8000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka